### ISSUE TITLE
What is Discordian Dates?

### ISSUE THREAD

**Issue by antofthy** [bo0ts/ddate#17]
It would be very helpful to have at least some mention in the top level README, Perhaps a introduction, that mentions...  **What the heck is a discordian date!**
Basically someone just following links to here, has no idea what you are talking about, or what the project is for.  A link to wikipedia (if it has something on it) would be adequate.

**Comment by danwdart** [comment]
We're mentioned on at least https://en.wikipedia.org/wiki/Discordian_calendar#Implementations

**Comment by bo0ts** [comment]
If you don't know, you shouldn't know.
