### ISSUE TITLE
PRs going unmerged, issues going undiscussed, has @bo0ts given up?

### ISSUE THREAD

**Issue by danwdart** [bo0ts/ddate#20]
Hmmmm, I volunteer to maintain if so.

**Comment by bo0ts** [comment]
Give me the weekend to think about it.

**Comment by bo0ts** [comment]
@danwdart Seems you gave up before you even tried ;)

**Comment by emberdart** [comment]
I think my notifications gave up... or my memory gave up, I'm not sure which happened first. I had to re-review everything here before I understood.
